### ISSUE TITLE
Add support for ConfTr

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/ConformalPrediction.jl#55]
This ICLR 2022 [paper](https://openreview.net/forum?id=t8O-4LKFVx) shows how to train conformal classifiers.

- [x] Add losses for prediction step (prediction step)
- [x] Streamline (need separate score method for dealing with `MLJFlux`) - *done in [b4c7140](https://github.com/JuliaTrustworthyAI/ConformalPrediction.jl/commit/b4c7140af7b49a21b35f9c60f5bc4a625e43b0d0)*
- [ ] Add support for differentiable quantile computations (calibration step)
- [ ] Implement batch training procedure
- [ ] Test and document

**Comment by pat-alt** [comment]
Some questions that have come up so far:

1. Is the Direc delta really supposed to be an indicator function? Equation (5) on page 5.
2. Doesn't the smooth size loss depend a lot on the scale of the (non-)conformity scores? For $E_{\theta}(x,k)=\pi_{\theta,k}(x)\in[0,1]$, for example, we have that $\sigma(E_{\theta}(x,k) - \tau) \in [0.27,0.73]$. We can use temperature scaling, but can we really speak of 'probabilities' that labels are assigned to the set?

**Comment by davidstutz** [comment]
Re:
1. You can find a reference implementation for Equation (5) [here](https://github.com/deepmind/conformal_training/blob/main/train_utils.py#L365).
2. Reference implementation for that is [here](https://github.com/deepmind/conformal_training/blob/main/train_utils.py#L263) - but this does indeed depend on the scale. That's what the temperature term $T$ is for: $\sigma((E_\theta(x, k) - \tau)/T)$. Also, you can use the log-probabilities $E_\theta(x, k) = \log \pi_{\theta,k}(x)$ which works a bit better in practice.
3. They can be penalized but this is generally not necessary. Basically, as long as there is one true label for each example, and $\alpha$ is reasonably low, the majority of prediction sets will contain at least the true label (so not be empty). This is mainly a result of the simple conformity score (for other conformal predictors this can be different). Beyond that, you are of course free to penalize that, but I am just saying that it is generally not required to learn good classifiers.
4. Gradients wrt. to what is the question? Generlly, gradient is not a problem as long as the sorting is fixed. The key is getting gradients *through* the sorting - this is what the smooth sorter is for.

Hope that helps. If I am slow to respond on here, feel free to send me an email to follow-up - always curious to see what people do with conformal training especially as I had some follow-up ideas but couldn't really pursue them.

**Comment by pat-alt** [comment]
Wow this was quick, thanks a lot 🙏

That all makes sense. Regarding the quantile computation, thanks for the clarification. For my current use case, I just need to differentiate with respect to a conformal model that has already been calibrated, but I see now why you need information about the sorting itself for training. 

Thanks again for being responsive!
