### ISSUE TITLE
Implement `EnbPI`

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/ConformalPrediction.jl#57]

**Comment by MojiFarmanbar** [comment]
here is the [paper](http://proceedings.mlr.press/v139/xu21h/xu21h.pdf) for EnbPI and [MAPIE](https://mapie.readthedocs.io/en/latest/theoretical_description_regression.html#the-jackknife-after-bootstrap-method) implementation and [example](https://mapie.readthedocs.io/en/latest/examples_regression/4-tutorials/plot_ts-tutorial.html)

**Comment by pat-alt** [comment]
Closed by #52
