### ISSUE TITLE
readme Quick Tour notebook: "Could not fetch rendered notebook or notebook source."

### ISSUE THREAD

**Issue by tfiers** [JuliaTrustworthyAI/ConformalPrediction.jl#97]
![image](https://github.com/JuliaTrustworthyAI/ConformalPrediction.jl/assets/3773558/43e108c9-680e-422f-b55e-03bb3770f37c)

**Comment by pat-alt** [comment]
Thanks, I think the link is broken. Will ask the JuliaHub folks.

**Comment by pat-alt** [comment]
@dattax maybe we can do this right here 😄 any idea why the link is no longer working?

**Comment by Dattax** [comment]
Can you check that this particulate notebook is in a folder marked as public?

**Comment by pat-alt** [comment]
Thanks, it seems to be working again! @tfiers can you confirm that https://juliahub.com/ui/Notebooks/juliahub/Tutorials/ConformalPrediction.jl works for you as well?

**Comment by tfiers** [comment]
It does, thank you!
